stages:
- build
- test
- sonarqube

build:
    stage: build
    script:
        - cd Idividual_project
        - ./gradlew build -x test
        - ./gradlew.bat --stop

test:
    stage: test
    script:
        - cd Idividual_project
        - ./gradlew test
        - ./gradlew.bat --stop

