stages:
- build
- test
- sonarqube

build:
    stage: build
    script:
        - cd Idividual_project
        - ./gradlew build -x test
        - ./gradlew.bat --stop

test:
    stage: test
    script:
        - cd Idividual_project
        - ./gradlew test
        - ./gradlew.bat --stop

sonarqube:
    stage: sonarqube
    script: 
        - cd Idividual_project
        - ./gradlew sonarqube -D'sonar.qualitygate.wait=true' -D 'sonar.projectKey=S3_Individual_Project' -D 'sonar.host.url=http://localhost:9000' -D 'sonar.login=a55dd730029a3cb2d69e73c50c95d16e72de0f58'
        - ./gradlew.bat --stop
