stages:
- build
- test
- sonarqube

build:
    stage: build
    script:
        - cd Idividual_project
        - ./gradlew build -x test
        - ./gradlew.bat --stop

test:
    stage: test
    script:
        - cd Idividual_project
        - ./gradlew test
        - ./gradlew.bat --stop

sonarqube:
  stage: sonarqube
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd Idividual_project 
    - gradle sonarqube
    - ./gradlew.bat --stop
  allow_failure: true
  only:
    - main
